spring.application.name=UrlShortener

# MySQL Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/urlshortener?useSSL=false
spring.datasource.username=root
spring.datasource.password=oZfn:aCV@DZ%qRk95jR^nTP#M
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
